spring.application.name=cloud-task

# gcp
spring.cloud.gcp.project-id=qwiklabs-gcp-00-fdc9ede00a14
spring.cloud.gcp.credentials.location=file:/home/clearmind/Downloads/qwiklabs-gcp-00-fdc9ede00a14-9e344ec03c8a.json
gcp.location.queue=${GCP_LOCATION}
gcp.queue-id=${GCP_QUEUE}

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html



